apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alerts.seq.k8s.datalust.co
spec:
  group: seq.k8s.datalust.co
  names:
    kind: Alert
    listKind: AlertList
    plural: alerts
    shortNames:
    - seqalert
    singular: alert
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              id:
                nullable: true
                type: string
              info:
                nullable: true
                properties:
                  title:
                    nullable: true
                    type: string
                  description:
                    nullable: true
                    type: string
                  ownerId:
                    nullable: true
                    type: string
                  protected:
                    nullable: true
                    type: boolean
                  disabled:
                    nullable: true
                    type: boolean
                  where:
                    nullable: true
                    type: string
                  groupBy:
                    items:
                      properties:
                        label:
                          nullable: true
                          type: string
                        value:
                          nullable: true
                          type: string
                        caseInsensitive:
                          nullable: true
                          type: boolean
                      type: object
                    nullable: true
                    type: array
                  timeGrouping:
                    nullable: true
                    type: string
                  select:
                    items:
                      properties:
                        label:
                          nullable: true
                          type: string
                        value:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  having:
                    nullable: true
                    type: string
                  notificationLevel:
                    enum:
                    - Verbose
                    - Debug
                    - Information
                    - Warning
                    - Error
                    - Fatal
                    nullable: true
                    type: string
                  notificationProperties:
                    additionalProperties:
                      nullable: false
                      type: string
                    nullable: true
                    type: object
                  suppressionTime:
                    nullable: true
                    type: string
                type: object
              conditions:
                items:
                  properties:
                    type:
                      nullable: true
                      type: string
                    status:
                      nullable: true
                      type: string
                    error:
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                  type: object
                nullable: false
                type: array
            type: object
          spec:
            nullable: false
            properties:
              policy:
                items:
                  enum:
                  - Create
                  - Update
                  - Delete
                  type: string
                nullable: true
                type: array
              instanceRef:
                nullable: true
                properties:
                  namespace:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                required:
                - name
                type: object
              find:
                nullable: true
                properties:
                  title:
                    nullable: true
                    type: string
                  ownerId:
                    nullable: true
                    type: string
                type: object
              init:
                nullable: true
                properties:
                  title:
                    nullable: true
                    type: string
                  description:
                    nullable: true
                    type: string
                type: object
              conf:
                nullable: true
                properties:
                  title:
                    nullable: true
                    type: string
                  description:
                    nullable: true
                    type: string
                type: object
            required:
            - instanceRef
            - conf
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}