apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apikeys.seq.k8s.datalust.co
spec:
  group: seq.k8s.datalust.co
  names:
    kind: ApiKey
    listKind: ApiKeyList
    plural: apikeys
    shortNames:
    - seqapikey
    singular: apikey
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              id:
                nullable: true
                type: string
              secretRef:
                nullable: true
                properties:
                  name:
                    nullable: false
                    type: string
                  namespace:
                    nullable: false
                    type: string
                type: object
              info:
                nullable: true
                properties:
                  tokenPrefix:
                    nullable: true
                    type: string
                  title:
                    nullable: true
                    type: string
                  isDefault:
                    nullable: true
                    type: boolean
                  ownerId:
                    nullable: true
                    type: string
                  permissions:
                    items:
                      enum:
                      - Undefined
                      - Public
                      - Ingest
                      - Read
                      - Write
                      - Setup
                      - Project
                      - System
                      - Organization
                      type: string
                    nullable: true
                    type: array
                  inputSettings:
                    nullable: true
                    properties:
                      appliedProperties:
                        additionalProperties:
                          nullable: false
                          type: string
                        nullable: true
                        type: object
                      filter:
                        nullable: true
                        properties:
                          description:
                            nullable: true
                            type: string
                          descriptionIsExcluded:
                            nullable: true
                            type: boolean
                          filter:
                            nullable: true
                            type: string
                          filterNonStrict:
                            nullable: true
                            type: string
                        type: object
                      minimumLevel:
                        enum:
                        - Verbose
                        - Debug
                        - Information
                        - Warning
                        - Error
                        - Fatal
                        nullable: true
                        type: string
                      useServerTimestamps:
                        nullable: true
                        type: boolean
                    type: object
                type: object
              conditions:
                items:
                  properties:
                    type:
                      nullable: true
                      type: string
                    status:
                      nullable: true
                      type: string
                    error:
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                  type: object
                nullable: false
                type: array
            type: object
          spec:
            nullable: false
            properties:
              instanceRef:
                nullable: true
                properties:
                  namespace:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                required:
                - name
                type: object
              secretRef:
                nullable: true
                properties:
                  name:
                    nullable: false
                    type: string
                  namespace:
                    nullable: false
                    type: string
                type: object
              find:
                nullable: true
                properties:
                  title:
                    nullable: true
                    type: string
                type: object
              conf:
                nullable: true
                properties:
                  title:
                    nullable: true
                    type: string
                  isDefault:
                    nullable: true
                    type: boolean
                  permissions:
                    items:
                      enum:
                      - Undefined
                      - Public
                      - Ingest
                      - Read
                      - Write
                      - Setup
                      - Project
                      - System
                      - Organization
                      type: string
                    nullable: true
                    type: array
                  inputSettings:
                    nullable: true
                    properties:
                      appliedProperties:
                        additionalProperties:
                          nullable: false
                          type: string
                        nullable: true
                        type: object
                      filter:
                        nullable: true
                        properties:
                          description:
                            nullable: true
                            type: string
                          descriptionIsExcluded:
                            nullable: true
                            type: boolean
                          filter:
                            nullable: true
                            type: string
                          filterNonStrict:
                            nullable: true
                            type: string
                        type: object
                      minimumLevel:
                        enum:
                        - Verbose
                        - Debug
                        - Information
                        - Warning
                        - Error
                        - Fatal
                        nullable: true
                        type: string
                      useServerTimestamps:
                        nullable: true
                        type: boolean
                    type: object
                type: object
            required:
            - instanceRef
            - conf
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}