apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instances.k8s.seq.datalust.co
spec:
  group: k8s.seq.datalust.co
  names:
    kind: Instance
    listKind: InstanceList
    plural: instances
    shortNames:
    - seqinstance
    singular: instance
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              deployment:
                nullable: true
                properties: {}
                type: object
              info:
                nullable: true
                properties:
                  enabledFeatures:
                    items:
                      nullable: false
                      type: string
                    nullable: true
                    type: array
                type: object
            type: object
          spec:
            nullable: false
            properties:
              policy:
                items:
                  enum:
                  - Create
                  - Update
                  - Delete
                  type: string
                nullable: true
                type: array
              connection:
                nullable: true
                properties:
                  endpoint:
                    nullable: true
                    type: string
                  login:
                    nullable: true
                    properties:
                      secretRef:
                        nullable: true
                        properties:
                          name:
                            nullable: false
                            type: string
                          namespace:
                            nullable: false
                            type: string
                        type: object
                    required:
                    - secretRef
                    type: object
                  apiKey:
                    nullable: true
                    properties:
                      secretRef:
                        nullable: true
                        properties:
                          name:
                            nullable: false
                            type: string
                          namespace:
                            nullable: false
                            type: string
                        type: object
                    required:
                    - secretRef
                    type: object
                required:
                - endpoint
                type: object
              deployment:
                nullable: true
                properties:
                  secretRef:
                    nullable: true
                    properties:
                      name:
                        nullable: false
                        type: string
                      namespace:
                        nullable: false
                        type: string
                    type: object
                required:
                - secretRef
                type: object
              init:
                nullable: true
                properties:
                  enabledFeatures:
                    items:
                      nullable: false
                      type: string
                    nullable: true
                    type: array
                type: object
              conf:
                nullable: true
                properties:
                  enabledFeatures:
                    items:
                      nullable: false
                      type: string
                    nullable: true
                    type: array
                type: object
            required:
            - conf
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}