apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instances.k8s.seq.datalust.co
spec:
  group: k8s.seq.datalust.co
  names:
    kind: Instance
    listKind: InstanceList
    plural: instances
    shortNames:
    - seqinstance
    singular: instance
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              id:
                nullable: true
                type: string
              lastConf:
                nullable: true
                type: string
            type: object
          spec:
            nullable: false
            properties:
              policy:
                items:
                  enum:
                  - Create
                  - Update
                  - Delete
                  type: string
                nullable: true
                type: array
              name:
                nullable: false
                type: string
              auth:
                nullable: true
                properties:
                  unknown:
                    nullable: true
                    type: string
                  secretRef:
                    nullable: true
                    properties:
                      name:
                        nullable: false
                        type: string
                      namespace:
                        nullable: false
                        type: string
                    type: object
                required:
                - unknown
                - secretRef
                type: object
              init:
                nullable: true
                properties:
                  value:
                    nullable: true
                    type: string
                type: object
              conf:
                nullable: true
                properties:
                  value:
                    nullable: true
                    type: string
                type: object
            required:
            - name
            - auth
            - conf
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}