apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: objects.k8s.seq.datalust.co
spec:
  group: k8s.seq.datalust.co
  names:
    kind: Object
    listKind: ObjectList
    plural: objects
    shortNames:
    - seqobject
    singular: object
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              id:
                nullable: true
                type: string
              lastConf:
                nullable: true
                type: string
            type: object
          spec:
            nullable: false
            properties:
              policy:
                items:
                  enum:
                  - Create
                  - Update
                  - Delete
                  type: string
                nullable: true
                type: array
              instanceRef:
                nullable: true
                properties:
                  namespace:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                required:
                - name
                type: object
              find:
                nullable: true
                properties: {}
                type: object
              init:
                nullable: true
                properties:
                  value:
                    nullable: true
                    type: string
                type: object
              conf:
                nullable: true
                properties:
                  value:
                    nullable: true
                    type: string
                type: object
            required:
            - instanceRef
            - conf
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}