apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: retentionpolicys.seq.k8s.datalust.co
spec:
  group: seq.k8s.datalust.co
  names:
    kind: RetentionPolicy
    listKind: RetentionPolicyList
    plural: retentionpolicys
    shortNames:
    - seqretentionpolicy
    singular: retentionpolicy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              id:
                nullable: true
                type: string
              info:
                nullable: true
                properties:
                  retentionTime:
                    nullable: true
                    type: string
                type: object
              conditions:
                items:
                  properties:
                    type:
                      nullable: true
                      type: string
                    status:
                      nullable: true
                      type: string
                    error:
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                  type: object
                nullable: false
                type: array
            type: object
          spec:
            nullable: false
            properties:
              policy:
                items:
                  enum:
                  - Create
                  - Update
                  - Delete
                  type: string
                nullable: true
                type: array
              instanceRef:
                nullable: true
                properties:
                  namespace:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                required:
                - name
                type: object
              init:
                nullable: true
                properties:
                  retentionTime:
                    nullable: true
                    type: string
                type: object
              conf:
                nullable: true
                properties:
                  retentionTime:
                    nullable: true
                    type: string
                type: object
            required:
            - instanceRef
            - conf
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}