apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: signals.seq.k8s.datalust.co
spec:
  group: seq.k8s.datalust.co
  names:
    kind: Signal
    listKind: SignalList
    plural: signals
    shortNames:
    - seqsignal
    singular: signal
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              id:
                nullable: true
                type: string
              info:
                nullable: true
                properties:
                  title:
                    nullable: true
                    type: string
                  description:
                    nullable: true
                    type: string
                  explicitGroupName:
                    nullable: true
                    type: string
                  isIndexSuppressed:
                    nullable: true
                    type: boolean
                  isProtected:
                    nullable: true
                    type: boolean
                  grouping:
                    enum:
                    - Inferred
                    - Explicit
                    - None
                    nullable: true
                    type: string
                  filters:
                    items:
                      properties:
                        description:
                          nullable: true
                          type: string
                        descriptionIsExcluded:
                          nullable: true
                          type: boolean
                        filter:
                          nullable: true
                          type: string
                        filterNonStrict:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  columns:
                    items:
                      properties:
                        expression:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                type: object
              conditions:
                items:
                  properties:
                    type:
                      nullable: true
                      type: string
                    status:
                      nullable: true
                      type: string
                    error:
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                  type: object
                nullable: false
                type: array
            type: object
          spec:
            nullable: false
            properties:
              instanceRef:
                nullable: true
                properties:
                  namespace:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                required:
                - name
                type: object
              conf:
                nullable: true
                properties:
                  title:
                    nullable: true
                    type: string
                  description:
                    nullable: true
                    type: string
                  explicitGroupName:
                    nullable: true
                    type: string
                  isIndexSuppressed:
                    nullable: true
                    type: boolean
                  isProtected:
                    nullable: true
                    type: boolean
                  grouping:
                    enum:
                    - Inferred
                    - Explicit
                    - None
                    nullable: true
                    type: string
                  filters:
                    items:
                      properties:
                        description:
                          nullable: true
                          type: string
                        descriptionIsExcluded:
                          nullable: true
                          type: boolean
                        filter:
                          nullable: true
                          type: string
                        filterNonStrict:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  columns:
                    items:
                      properties:
                        expression:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                type: object
            required:
            - instanceRef
            - conf
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}