apiVersion: v2
name: seq-operator
description: Operator that manages a Seq instances.
type: application
version: 0.0.0
appVersion: "0.0.0"
keywords:
  - seq
home: https://github.com/alethic/seq-operator
sources:
  - https://github.com/alethic/seq-operator
maintainers:
  - name: Jerome Haltom
    email: jhaltom@alethic.solutions
