apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seq-operator.fullname" . }}
  labels:
    {{- include "seq-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
