apiVersion: v1
kind: ServiceAccount
metadata:
  name: seq-operator
  namespace: {{ .Release.Namespace }}
  labels: {{- include "seq-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
