apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seq:view
  labels:
    {{- include "seq-operator.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - seq.k8s.datalust.co
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
---
