apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: seq-init-scripts
  files:
  - init.sh
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: seq-admin-password
  files:
  - password=password.txt
  options:
    disableNameSuffixHash: true
  type: Opaque

helmCharts:
- name: seq
  repo: https://helm.datalust.co
  releaseName: seq
  valuesFile: values.yaml
